Lesson 5, 26.07.22
Lushnikov-N-A/TestGuru pull request #9
Opened 2022-07-26 21:17 UTC by Lushnikov-N-A

Lesson 5. 26.07.22

2022-07-27 06:57 UTC, VidgarVii requested changes

2022-07-27 06:57 UTC, VidgarVii commented on app/models/category.rb
> +  has_many :tests
если категорию удалить, то в текущем варианте можно в дальнейшем получить ошибку

к примеру при попытке обратиться по ассоциации (`@test.category`)
или при каких-то операциях, которые подразумевают валидацию объекта

после удаления категории в таблице `tests` останется в поле `category_id` ссылка на несуществующий объект
т.е. объекты в таблице `tests` станут невалидными: рельсы по умолчанию проверяют наличие ассоциированного объекта для всех `belongs_to` ассоциаций (при валидации этого объекта) и выбрасывают ошибку валидации, если объекта не существует

если же на уровне бд поле `category_id` обозначено, как внешний ключ, то уже на попытке удаления объекта из таблицы `categories` получим ошибку базы данных, такого примерно вида:
```
ActiveRecord::InvalidForeignKey (PG::ForeignKeyViolation: EROR:  update or delete on table "categories" violates foreign key constraint
```
и рельсы откажутся удалять категорию

поэтому для всех `has_*` ассоциаций следует указывать поведение при удалении - можно посмотреть в документации - опция `dependent: ...`

2022-07-27 06:57 UTC, VidgarVii commented on app/models/question.rb
> +  has_many :answers
belongs_to и has_many разделяют пустыми строками. Такое разделение кода на логические блоки.
Пример оформления модели можно посмотреть тут https://github.com/rubocop/rails-style-guide#macro-style-methods

2022-07-27 06:57 UTC, VidgarVii commented on app/models/test.rb
>    end
с использованием ассоциации `joins` можно сильно сократить
в задании "Ассоциации моделей" самое время это сделать

***
```ruby
  joins(:category)
    .where(categories: { title: test_category })
    .order(title: :desc)
    .pluck(:title)
```

2022-07-27 06:57 UTC, VidgarVii commented on app/models/test.rb
> +
нет связи с автором и Между Тестами и проходящими их Пользователями (учесть, что один и тот же тест могут проходить несколько пользователей одновременно)

2022-07-27 06:57 UTC, VidgarVii commented on app/models/user.rb
> +  has_many :author, class_name: 'Test', foreign_key: :author_id
тут можно подумать так, что юзер имеет много авторов?!

2022-07-27 06:57 UTC, VidgarVii commented on app/models/user.rb
> +  has_many :author, class_name: 'Test', foreign_key: :author_id
нет связи с пройденными тестами

2022-07-29 05:49 UTC, BubuntuClu requested changes

2022-07-29 05:49 UTC, BubuntuClu commented on app/models/answer.rb
> +  belongs_to :question, optional: true
`optional: true` ты предполагаешь что ответ может быть без привязки к вопросу? а какой в этом смысл? таким образом ответ нигде не будет фигурировать. эта опция тут лишняя, надо ее удалить

2022-07-29 05:49 UTC, BubuntuClu commented on app/models/question.rb
> +  belongs_to :test, optional: true
тоже самое и тут. вопрос должен быть привязан к тесту

2022-07-29 05:49 UTC, BubuntuClu commented on app/models/test_passing.rb
> +  belongs_to :user, optional: true
и тут. в строках этой таблицы нет смысла, если одна из колонок будет пустой

2022-07-29 05:49 UTC, BubuntuClu commented on app/models/user.rb
> +  belongs_to :test, optional: true
пользователь не принадлежит тесту. это тест принадлежит автору.

2022-07-29 05:49 UTC, BubuntuClu commented on app/models/user.rb
> +  has_many :test_passings, dependent: :destroy # "нет связи с пройденными тестами" - вот этот комментарий не понял, тут же, можно сказать, "прямая" связь?
я думаю тут имелось в виду то, чтобы ты мог получить список тестов, которые проходил этот пользователь. такой ассоциации действительно нет

2022-07-29 05:49 UTC, BubuntuClu commented on app/models/test.rb
> +  belongs_to :user, optional: true
что возвращает эта ассоциация?
чем она отличается от `author`?

2022-07-29 05:49 UTC, BubuntuClu commented on app/models/test.rb
> +  belongs_to :category, optional: true
optional лишнее

2022-07-29 20:05 UTC, Lushnikov-N-A commented on app/models/answer.rb
> +  belongs_to :question, optional: true
optional: true - везде пришлось добавить, т.к. после удаления/воссоздания БД и попытки выполнить db:seed посыпались разные ошибки active records, на мой взгляда вообще не связанные с выполненными действиями: с начала по локали :ru, потом по связям. Устранилось в итоге все добавлением данной опции.
Насколько я понимаю, данная опция отключает валидацию наличия связанного объекта с другим, что вроде бы подтвердилось практикой. После восстановления БД, скорее всего, ее можно и удалить.

2022-07-29 20:14 UTC, Lushnikov-N-A commented on app/models/user.rb
> +  has_many :test_passings, dependent: :destroy # "нет связи с пройденными тестами" - вот этот комментарий не понял, тут же, можно сказать, "прямая" связь?
Складывается ощущение, что имеет место какое-то недопонимание, пример работы:
```
2.7.4 :006 > user.test_passings
 => 
[#<TestPassing:0x00007fdf443402f8
  id: 6,
  user_id: 5,
  test_id: 6,
  correct_questions: 2,
  created_at: Fri, 29 Jul 2022 01:48:25.192299000 +05 +05:00,
  updated_at: Fri, 29 Jul 2022 01:48:25.192299000 +05 +05:00>,
 #<TestPassing:0x00007fdf442668a0
  id: 7,
  user_id: 5,
  test_id: 7,
  correct_questions: 1,
  created_at: Fri, 29 Jul 2022 01:48:25.200246000 +05 +05:00,
  updated_at: Fri, 29 Jul 2022 01:48:25.200246000 +05 +05:00>,
 #<TestPassing:0x00007fdf442665f8
  id: 8,
  user_id: 5,
  test_id: 9,
  correct_questions: 1,
  created_at: Fri, 29 Jul 2022 01:48:25.210507000 +05 +05:00,
  updated_at: Fri, 29 Jul 2022 01:48:25.210507000 +05 +05:00>,
 #<TestPassing:0x00007fdf44266468
  id: 10,
  user_id: 5,
  test_id: 10,
  correct_questions: 3,
  created_at: Fri, 29 Jul 2022 01:48:25.229617000 +05 +05:00,
  updated_at: Fri, 29 Jul 2022 01:48:25.229617000 +05 +05:00>] 
2.7.4 :007 > user2 = User.second
  User Load (0.2ms)  SELECT "users".* FROM "users" ORDER BY "users"."id" ASC LIMIT ? OFFSET ?  [["LIMIT", 1], ["OFFSET", 1]]
 =>                                      
#<User:0x000055cac448d0e8                
...                                      
2.7.4 :008 > user2.test_passings
  TestPassing Load (0.2ms)  SELECT "test_passings".* FROM "test_passings" WHERE "test_passings"."user_id" = ?  [["user_id", 6]]
 =>                                      
[#<TestPassing:0x000055cac4366200        
  id: 9,                                 
  user_id: 6,
  test_id: 6,
  correct_questions: 1,
  created_at: Fri, 29 Jul 2022 01:48:25.221321000 +05 +05:00,
  updated_at: Fri, 29 Jul 2022 01:48:25.221321000 +05 +05:00>] 
2.7.4 :009 > 

```

2022-07-29 20:18 UTC, Lushnikov-N-A commented on app/models/user.rb
> +  has_many :test_passings, dependent: :destroy # "нет связи с пройденными тестами" - вот этот комментарий не понял, тут же, можно сказать, "прямая" связь?
Задание: _Между Тестами и проходящими их Пользователями (учесть, что один и тот же тест могут проходить несколько пользователей одновременно)_
Что не так? 
Все работает в рамках логики и задания.

2022-07-29 20:22 UTC, Lushnikov-N-A commented on app/models/user.rb
> +  has_many :test_passings, dependent: :destroy # "нет связи с пройденными тестами" - вот этот комментарий не понял, тут же, можно сказать, "прямая" связь?
Я не понимаю, что требуется переделать? У каждого возможен свой взгляд на неточное ТЗ. (_"я думаю тут имелось в виду то, чтобы ты мог получить список тестов, которые проходил этот пользователь. такой ассоциации действительно нет"_) Собственно, именно это и реализовано.

2022-07-29 21:08 UTC, Lushnikov-N-A commented on app/models/question.rb
> +  belongs_to :test, optional: true
Тоже самое, первый коммент.

2022-07-29 21:08 UTC, Lushnikov-N-A commented on app/models/test_passing.rb
> +  belongs_to :user, optional: true
Чуть выше.

2022-07-29 21:12 UTC, Lushnikov-N-A commented on app/models/test.rb
> +  belongs_to :user, optional: true
_test.users_ возвращает пользователей, прошедших данный тест:
```
2.7.4 :009 > test = Test.first
  Test Load (0.2ms)  SELECT "tests".* FROM "tests" ORDER BY "tests"."id" ASC LIMIT ?  [["LIMIT", 1]]
 =>                                                                
#<Test:0x00007fdf446c8268                                          
...                                                                
2.7.4 :010 > test.users
  User Load (0.5ms)  SELECT "users".* FROM "users" INNER JOIN "test_passings" ON "users"."id" = "test_passings"."user_id" WHERE "test_passings"."test_id" = ?  [["test_id", 6]]
 =>                                                                
[#<User:0x000055cac433f060                                         
  id: 5,                                                           
  nickname: "Alex K",                                              
  login: "Alex1111",                                               
  password: "[FILTERED]",                                          
  role: "admin",                                                   
  email: "admin@testguru.com",                                     
  created_at: Fri, 29 Jul 2022 01:48:24.392030000 +05 +05:00,      
  updated_at: Fri, 29 Jul 2022 01:48:24.392030000 +05 +05:00>,  
 #<User:0x000055cac433ef70                                      
  id: 6,                                                        
  nickname: "John W",                                           
  login: "johnnn",                                              
  password: "[FILTERED]",
  role: "user",
  email: "johnwast@gmail.com",
  created_at: Fri, 29 Jul 2022 01:48:24.400242000 +05 +05:00,
  updated_at: Fri, 29 Jul 2022 01:48:24.400242000 +05 +05:00>] 
2.7.4 :011 > 
```

2022-07-29 21:14 UTC, Lushnikov-N-A commented on app/models/test.rb
> +  belongs_to :user, optional: true
_test.author_ возвращает автора теста:
```
2.7.4 :011 > test.author
  User Load (0.3ms)  SELECT "users".* FROM "users" WHERE "users"."id" = ? LIMIT ?  [["id", 6], ["LIMIT", 1]]
 =>                                                             
#<User:0x000055cac446f200                                       
 id: 6,                                                         
 nickname: "John W",                                            
 login: "johnnn",                                               
 password: "[FILTERED]",                                        
 role: "user",                                                  
 email: "johnwast@gmail.com",                                   
 created_at: Fri, 29 Jul 2022 01:48:24.400242000 +05 +05:00,    
 updated_at: Fri, 29 Jul 2022 01:48:24.400242000 +05 +05:00>    
2.7.4 :012 > 

```

2022-07-29 21:16 UTC, Lushnikov-N-A commented on app/models/test.rb
> +  belongs_to :category, optional: true
см.выше.

2022-07-29 21:20 UTC, Lushnikov-N-A commented on app/models/user.rb
> +  belongs_to :test, optional: true
> пользователь не принадлежит тесту. это тест принадлежит автору.

_belongs_to :test, optional: true_ если речь идет об этом, то это необходимо для корректной работы _has_many :users, through: :test_passings_ для себя я это "объяснил" "проходные связи связей"

2022-07-31 11:44 UTC, closed without merging